### ISSUE TITLE
Component File Upload

### ISSUE THREAD

**Issue by dalmadima** [darenegade/tta-store#1]
Funktion zum upload von Dateien.
Felder:
Name
Beschreibung 
Kompabilität: mit welcher Version von TTA kompatibel
Schlagwörter:
Preis:

**Comment by dalmadima** [comment]
Wie siehts jetzt aus?

**Comment by dalmadima** [comment]
bitte beachten:
Units erstellen
**Die Kunden können entscheiden, ob sie die erstellten Units allen, einem Teil oder nur internen Nutzern zur Verfügung stellen.
Kunden können entscheiden, ob erstellte Units veränderbar oder unveränderbar sind.**

**Comment by Maxl94** [comment]
ist alles drin bitte mal drüberschauen

**Comment by dalmadima** [comment]
![tta_upload](https://user-images.githubusercontent.com/19187472/37169359-00da4656-2308-11e8-93ae-5be29b2126f7.png)
Hab die Upload Funktion ziemlich suchen müssen...
In Chrome seh ich garnichts
Es Fehlt noch das "support" Feld.. Also welche Core Version. supported wird.

**Comment by Maxl94** [comment]
Ich bin gerade dabei des auf eine extra Seite zu machen. Wie definiere ich in meinem Template die Route? Also dass auf ".../upload-detail" auch meine Seite aufgerufen wird? Polymer Dokumentation ist nicht so hilfreich.

**Comment by darenegade** [comment]
Upload funktioniert siehe PR
