### ISSUE TITLE
Unit-Liste Daten

### ISSUE THREAD

**Issue by darenegade** [darenegade/tta-store#12]
Felder:
* Name
* Datum (Version)
* Version
* Preis
* Beschreibung
* Logo
* Author
* Kompatibilität (TTA Versionen)

**Comment by peter-mueller** [comment]
Logo fehlt noch, die bilder dazu generell

**Comment by darenegade** [comment]
Es fehlen auch noch 2 hidden Felder: 
* restriction - Einschränkung der Sichtbarkeit z.B. durch Wert `bmw`, für Mandantenfähigkeit
* owned - Boolean ob man es schon gekauft hat

**Comment by darenegade** [comment]
Wurde auch erledigt
