### ISSUE TITLE
Kaufen/Download aus Unit-Detail

### ISSUE THREAD

**Issue by darenegade** [darenegade/tta-store#13]
Das Alert vom Download sollte durch etwas passenderes ersetzt werden

**Comment by darenegade** [comment]
BLOCKER: Hängt an Lizenzmodell, ob es erst gekauft werden muss oder gleich runtergeladen werden kann

**Comment by dalmadima** [comment]
bitte beachten:

Units erwerben
**Units können kostenlos oder gegen einen Festpreis pro Lizenz erworben werden, der durch den Ersteller der Unit festgelegt wird.
Telemotive erhält einen Anteil an jedem Unit-Verkauf (Bei Modell “Open” geringer als im Modell “Protected”).
Units sind nur für die Lizenz gültig, für die sie gekauft wurden. Bei Verlängerung der Lizenz verlängert sich auch die Nutzungsdauer der Units.**

**Comment by dalmadima** [comment]
Das Modell sollte eventuell dahingehend erweitert werden, dass jede Unit ein Lizenzmodell bekommt

**Comment by darenegade** [comment]
Sollte nicht mehr relevant sein
