### ISSUE TITLE
Component login

### ISSUE THREAD

**Issue by dalmadima** [darenegade/tta-store#2]
Login Funktion mit email passwort

**Comment by dalmadima** [comment]
Bitte auch unterscheiden zwischen verschiedenen Rollen
Normal User und User der Bestellen kann

**Comment by GhostMST** [comment]
#11

**Comment by dalmadima** [comment]
Offizielle Aussage: Store ist nicht öffentlich zugänglich

**Comment by darenegade** [comment]
Wurde mit https://github.com/darenegade/tta-store/pull/11 erledigt
