### ISSUE TITLE
Backend Mockup

### ISSUE THREAD

**Issue by dalmadima** [darenegade/tta-store#4]
Also es wäre einen Backend Mockup zu schreiben 
User Übersicht... (mit jeweiliger Übersicht über Lizenzen und TTAUnits)
TTAUnits übersicht.. mit Name, Beschreibung, Preis..
TTAUnit upload Funktion: (bitte mit anderen absprechen.. Frontend hat sowas auch)

**Comment by darenegade** [comment]
Hierzu gibt es im Repo einen Ordner `model` mit die die jeweiligen Daten des Backends als JSON Dateien enthalten soll. Änderungen werden dann in globalen Variablen gespeichert und an die Komponenten über bidirektionales Databinding weitergegeben

**Comment by darenegade** [comment]
Dieses Thema hat sich aus meiner Sicht erledigt
